export const GET_INTERVIEWER = "GET_INTERVIEWER";
export const UPDATE_INTERVIEWER ="UPDATE_INTERVIEWER";
export const ADD_INTERVIEWER = "ADD_INTERVIEWER";
export const SELECT_INTERVIEWER = "SELECT_INTERVIEWER";

export const GET_CANDIDATE = "GET_CANDIDATE";
export const ADD_CANDIDATE = "ADD_CANDIDATE";
export const SELECT_CANDIDATE = "SELECT_CANDIDATE";
export const UNSELECT_CANDIDATE = "UNSELECT_CANDIDATE";

export const GET_SKILLS = "GET_SKILLS";
export const ADD_SKILLS = "ADD_SKILLS";
export const FAIL_SKILLS = "FAIL_SKILLS";

export const GET_QUESTIONS = "GET_QUESTIONS";
export const SEND_QUESTIONS = "SEND_QUESTIONS";

export const ADD_COMMENTS = "ADD_COMMENTS";